import { escapeHtml, layout, accountHeader, footer } from "./layout.js";
import { INDIAN_STATES } from "../public/commerce-rules.js";

const esc = escapeHtml;
const rupees = (paise) => (Math.max(0, Number(paise) || 0) / 100).toFixed(2);
const baseStyles = `<style>
.checkout-settings{max-width:760px}.checkout-settings .settings-card{padding:clamp(22px,4vw,38px);background:var(--white);border:1px solid #e5ded2;box-shadow:0 14px 45px rgba(55,58,42,.05)}.checkout-settings h2{font:500 25px var(--serif);margin:27px 0 14px}.checkout-settings h2:first-child{margin-top:0}.settings-field{display:grid;gap:7px;margin:0 0 17px}.settings-field>label,.settings-label{font-weight:700;font-size:12px}.settings-field input,.settings-field select{height:46px;width:100%;padding:0 12px;border:1px solid #cfc7b9;border-radius:3px;background:var(--white);color:var(--ink)}.settings-help{color:var(--muted);font-size:11px}.settings-select{max-width:340px}.settings-row{display:grid;grid-template-columns:1fr 1fr;gap:14px}.settings-toggle{display:flex;align-items:flex-start;gap:11px;padding:15px 0;border-block:1px solid var(--line);margin:8px 0 18px}.settings-toggle input{width:19px;height:19px;accent-color:var(--green);margin:2px 0 0}.settings-toggle strong{display:block;font-size:12px}.settings-toggle span{font-size:11px;color:var(--muted)}.settings-actions{display:flex;align-items:center;gap:14px;margin-top:24px}.settings-status{font-size:11px;color:var(--muted)}.settings-error{padding:12px;background:#fae5dc;color:#743d30;border-left:3px solid var(--coral);font-size:12px}.orders-table-wrap{overflow:auto;border-top:1px solid var(--line)}.orders-table{width:100%;border-collapse:collapse;text-align:left}.orders-table th,.orders-table td{padding:15px 13px;border-bottom:1px solid var(--line);font-size:12px;white-space:nowrap}.orders-table th{color:var(--muted);font-size:10px;letter-spacing:.1em;text-transform:uppercase}.orders-empty{padding:46px 22px;text-align:center;border:1px dashed #b9c1a4;background:#f1eedf}.orders-empty h2{font:500 29px var(--serif);margin:8px}.orders-empty p{color:var(--muted);font-size:13px}.orders-status{display:inline-block;padding:5px 9px;background:#e8ead7;border-radius:99px;font-size:10px;font-weight:700;text-transform:capitalize}.order-reference{font-weight:700}@media(max-width:600px){.settings-row{grid-template-columns:1fr}.settings-actions{align-items:flex-start;flex-direction:column}.orders-table th,.orders-table td{padding:12px 9px}}
</style>`;
function documentPage(title, store, user, content, script = false) {
  const name = store?.name || "Your store";
  return layout({
    title: `${title} | ${name} | LeBrands.Store`,
    description: `${title} for ${name}.`,
    canonical: `https://app.lebrands.store/stores/${encodeURIComponent(store?.store_id || "")}/${title === "Orders" ? "orders" : "settings/checkout"}`,
    noindex: true,
    extraHead: `${baseStyles}${script ? '<script type="module" src="/assets/commerce.js"></script>' : ""}`,
    body: `${accountHeader(user)}<main class="wrap dashboard-main"><div class="dashboard-title"><div><div class="eyebrow">${esc(name)}</div><h1>${esc(title)}.</h1><p>${title === "Orders" ? "A read-only view of customer orders." : "Set delivery, Cash on Delivery and your GST location."}</p></div><div class="dashboard-actions"><a class="quiet-button" href="/">Back to your stores</a></div></div>${content}</main>${footer()}`,
  });
}
export function renderCheckoutSettings({ store = {}, settings = {} } = {}, user) {
  const delivery = ["free","flat","free_above"].includes(settings.delivery_mode) ? settings.delivery_mode : "free";
  const options = INDIAN_STATES.map(({code,name}) => `<option value="${esc(code)}" ${settings.store_state === code ? "selected" : ""}>${esc(name)}</option>`).join("");
  const body = `<form class="settings-card" data-checkout-settings data-store-id="${esc(store.store_id || "")}">
    <h2>Delivery</h2><div class="settings-field"><label for="delivery-mode">Delivery charge</label><select id="delivery-mode" class="settings-select" name="delivery_mode"><option value="free" ${delivery==="free"?"selected":""}>Free delivery</option><option value="flat" ${delivery==="flat"?"selected":""}>Flat charge</option><option value="free_above" ${delivery==="free_above"?"selected":""}>Free above an order value</option></select></div>
    <div class="settings-field" data-delivery-field="flat" ${delivery!=="flat"?"hidden":""}><label for="flat-rupees">Flat delivery charge (₹)</label><input id="flat-rupees" name="flat_rupees" inputmode="decimal" value="${rupees(settings.flat_paise)}" placeholder="e.g. 60.00"><span class="settings-help">Enter rupees with up to two decimal places.</span></div>
    <div class="settings-field" data-delivery-field="free_above" ${delivery!=="free_above"?"hidden":""}><label for="free-above-rupees">Free delivery from (₹)</label><input id="free-above-rupees" name="free_above_rupees" inputmode="decimal" value="${rupees(settings.free_above_paise)}" placeholder="e.g. 999.00"><span class="settings-help">Orders below this value use the flat delivery charge.</span></div>
    <div class="settings-field" data-delivery-field="free_above" ${delivery!=="free_above"?"hidden":""}><label for="threshold-flat-rupees">Charge below threshold (₹)</label><input id="threshold-flat-rupees" name="free_above_flat_rupees" inputmode="decimal" value="${rupees(settings.flat_paise)}" placeholder="e.g. 60.00"></div>
    <h2>Cash on Delivery</h2><label class="settings-toggle"><input type="checkbox" name="cod_enabled" ${settings.cod_enabled !== false ? "checked" : ""}><span><strong>Accept Cash on Delivery</strong><span>Customers pay when the order arrives.</span></span></label>
    <div class="settings-field"><label for="cod-max-rupees">Maximum COD order value (₹)</label><input id="cod-max-rupees" name="cod_max_rupees" inputmode="decimal" value="${rupees(settings.cod_max_paise ?? 300000)}"><span class="settings-help">COD orders above this value will be declined.</span></div>
    <h2>GST location</h2><div class="settings-field"><label for="store-state">State or Union Territory</label><select id="store-state" class="settings-select" name="store_state"><option value="">Choose state or UT</option>${options}</select><span class="settings-help">Used to determine whether customer GST is intra-state or inter-state.</span></div>
    <p class="settings-error" data-settings-error role="alert" hidden></p><div class="settings-actions"><button type="submit" class="button">Save checkout settings</button><span class="settings-status" data-settings-status role="status"></span></div>
  </form>`;
  return documentPage("Checkout settings", store, user, body, true);
}
export function renderOrders({ store = {}, orders = [] } = {}, user) {
  const rows = Array.isArray(orders) ? orders : [];
  const content = rows.length ? `<div class="orders-table-wrap"><table class="orders-table"><thead><tr><th>Order</th><th>Date</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th></tr></thead><tbody>${rows.map((order)=>`<tr><td class="order-reference">${esc(order.order_number || "Order")}</td><td>${esc(order.created_at ? new Date(order.created_at).toLocaleDateString("en-IN") : "Date unavailable")}</td><td>${esc(order.customer_name || order.name || "Customer")}<br><span class="settings-help">${esc(order.phone || "")}</span></td><td>${Number(order.item_count ?? order.items_count ?? 0)}</td><td>₹${(Math.max(0,Number(order.total_paise)||0)/100).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}</td><td><span class="orders-status">${esc(String(order.status || "confirmed_cod").replace(/_/g," "))}</span></td></tr>`).join("")}</tbody></table></div>` : `<section class="orders-empty"><span class="eyebrow">Your next order starts here</span><h2>No orders yet.</h2><p>Orders placed by your customers will appear here.</p></section>`;
  return documentPage("Orders", store, user, content);
}
