kind = "api"
previewPath = "/"
title = "LeBrands.Store"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/"]

[services.development]
run = "pnpm exec wrangler dev --local --config ../../wrangler.preview.jsonc --ip 0.0.0.0 --port $PORT"
